%% OFDM Wireless Communication System
% Performance Analysis of QPSK and 16-QAM OFDM
% over Static Rayleigh and Doppler Rayleigh Channels

clc;                    % Clears the Command Window.
clear;                  % Removes old variables from the workspace.
close all;              % Closes all previously opened figures.

%% ============================================================
%  COMMON PARAMETERS
% =============================================================

NFFT = 64;              % Number of OFDM subcarriers.
cpLength = 16;          % Length of the cyclic prefix.
SNR_values = 0:5:30;    % SNR values from 0 dB to 30 dB.
numFrames = 500;        % Number of OFDM frames simulated for each SNR.

%% ============================================================
%  PART 1: QPSK + TWO-PATH STATIC RAYLEIGH
% =============================================================

% Create an array to store QPSK BER values.
BER_QPSK_Rayleigh = zeros(size(SNR_values));

% Repeat the experiment for every SNR value.
for i = 1:length(SNR_values)

    % Set the current SNR.
    currentSNR = SNR_values(i);

    % Reset the total error counter.
    totalErrors = 0;

    % Reset the total transmitted-bit counter.
    totalBits = 0;

    % Create a two-path static Rayleigh channel.
    qpskChannel = comm.RayleighChannel( ...
        SampleRate=1e6, ...
        PathDelays=[0 1e-6], ...
        AveragePathGains=[0 -3], ...
        MaximumDopplerShift=0, ...
        PathGainsOutputPort=true);

    % Get information about the channel.
    qpskInfo = info(qpskChannel);

    % Get the channel filter coefficients.
    qpskPathFilters = qpskInfo.ChannelFilterCoefficients;

    % Get the channel timing offset.
    qpskTimingOffset = qpskInfo.ChannelFilterDelay;

    % Repeat the transmission many times.
    for frame = 1:numFrames

        % Generate random binary data.
        frameBits = randi([0 1], NFFT * 2, 1);

        % Modulate the bits using QPSK.
        frameSymbols = pskmod( ...
            frameBits, ...
            4, ...
            pi/4, ...
            InputType="bit");

        % Arrange QPSK symbols into one OFDM symbol.
        frameSymbols = reshape(frameSymbols, NFFT, 1);

        % Perform OFDM modulation and add cyclic prefix.
        frameWithCP = ofdmmod( ...
            frameSymbols, ...
            NFFT, ...
            cpLength);

        % Pass the OFDM signal through the Rayleigh channel.
        [fadedSignal, pathGains] = ...
            qpskChannel(frameWithCP);

        % Compensate for the channel timing offset.
        fadedSignalSync = [ ...
            fadedSignal(qpskTimingOffset+1:end); ...
            zeros(qpskTimingOffset,1)];

        % Add AWGN noise.
        receivedSignal = awgn( ...
            fadedSignalSync, ...
            currentSNR, ...
            'measured');

        % Calculate the actual OFDM channel frequency response.
        channelResponse = ofdmChannelResponse( ...
            pathGains, ...
            qpskPathFilters, ...
            NFFT, ...
            cpLength, ...
            1:NFFT, ...
            qpskTimingOffset);

        % Convert the channel response into a column vector.
        channelResponse = reshape( ...
            channelResponse, ...
            NFFT, 1);

        % Perform OFDM demodulation.
        receivedSymbols = ofdmdemod( ...
            receivedSignal, ...
            NFFT, ...
            cpLength, ...
            cpLength/2);

        % Convert received symbols into a column vector.
        receivedSymbols = reshape( ...
            receivedSymbols, ...
            NFFT, 1);

        % Equalize the received symbols using the channel response.
        equalizedSymbols = ...
            receivedSymbols ./ channelResponse;

        % Demodulate the equalized symbols using QPSK.
        receivedBits = pskdemod( ...
            equalizedSymbols, ...
            4, ...
            pi/4, ...
            OutputType="bit");

        % Calculate the number of bit errors.
        [frameErrors, ~] = biterr( ...
            frameBits, ...
            receivedBits);

        % Add this frame's errors to the total.
        totalErrors = totalErrors + frameErrors;

        % Add this frame's transmitted bits to the total.
        totalBits = totalBits + length(frameBits);

    end

    % Calculate BER for the current SNR.
    BER_QPSK_Rayleigh(i) = ...
        totalErrors / totalBits;

end

%% ============================================================
%  PART 2: 16-QAM + AWGN
% =============================================================

% Create an array to store 16-QAM AWGN BER values.
BER_16QAM_AWGN = zeros(size(SNR_values));

% Repeat the experiment for every SNR value.
for i = 1:length(SNR_values)

    % Set the current SNR.
    currentSNR = SNR_values(i);

    % Reset total errors.
    totalErrors = 0;

    % Reset total transmitted bits.
    totalBits = 0;

    % Repeat the experiment for many frames.
    for frame = 1:numFrames

        % Generate random bits.
        frameBits = randi([0 1], NFFT * 4, 1);

        % Modulate the bits using 16-QAM.
        frameSymbols = qammod( ...
            frameBits, ...
            16, ...
            InputType="bit", ...
            UnitAveragePower=true);

        % Arrange QAM symbols into one OFDM symbol.
        frameSymbols = reshape( ...
            frameSymbols, ...
            NFFT, 1);

        % Perform IFFT to create the OFDM time-domain signal.
        frameTimeSignal = ifft( ...
            frameSymbols, ...
            NFFT);

        % Take the last samples to create the cyclic prefix.
        cyclicPrefix = ...
            frameTimeSignal(end-cpLength+1:end);

        % Add the cyclic prefix to the OFDM signal.
        frameWithCP = ...
            [cyclicPrefix; frameTimeSignal];

        % Add AWGN noise.
        receivedSignal = awgn( ...
            frameWithCP, ...
            currentSNR, ...
            'measured');

        % Remove the cyclic prefix.
        receivedWithoutCP = ...
            receivedSignal(cpLength+1:end);

        % Perform FFT to recover the frequency-domain symbols.
        receivedSymbols = fft( ...
            receivedWithoutCP, ...
            NFFT);

        % Demodulate the 16-QAM symbols.
        receivedBits = qamdemod( ...
            receivedSymbols, ...
            16, ...
            OutputType="bit", ...
            UnitAveragePower=true);

        % Calculate the number of bit errors.
        [frameErrors, ~] = biterr( ...
            frameBits, ...
            receivedBits);

        % Accumulate the errors.
        totalErrors = ...
            totalErrors + frameErrors;

        % Accumulate the transmitted bits.
        totalBits = ...
            totalBits + length(frameBits);

    end

    % Calculate BER for the current SNR.
    BER_16QAM_AWGN(i) = ...
        totalErrors / totalBits;

end

%% ============================================================
%  PART 3: 16-QAM + TWO-PATH STATIC RAYLEIGH
% =============================================================

% Create an array to store 16-QAM Rayleigh BER values.
BER_16QAM_Rayleigh = zeros(size(SNR_values));

% Repeat the experiment for every SNR value.
for i = 1:length(SNR_values)

    % Set the current SNR.
    currentSNR = SNR_values(i);

    % Reset total errors.
    totalErrors = 0;

    % Reset total transmitted bits.
    totalBits = 0;

    % Create the two-path static Rayleigh channel.
    qamChannel = comm.RayleighChannel( ...
        SampleRate=1e6, ...
        PathDelays=[0 1e-6], ...
        AveragePathGains=[0 -3], ...
        MaximumDopplerShift=0, ...
        PathGainsOutputPort=true);

    % Get channel information.
    qamInfo = info(qamChannel);

    % Get channel filter coefficients.
    qamPathFilters = ...
        qamInfo.ChannelFilterCoefficients;

    % Get channel timing offset.
    qamTimingOffset = ...
        qamInfo.ChannelFilterDelay;

    % Simulate many OFDM frames.
    for frame = 1:numFrames

        % Generate random bits.
        frameBits = randi( ...
            [0 1], ...
            NFFT * 4, ...
            1);

        % Perform 16-QAM modulation.
        frameSymbols = qammod( ...
            frameBits, ...
            16, ...
            InputType="bit", ...
            UnitAveragePower=true);

        % Arrange the symbols into an OFDM symbol.
        frameSymbols = reshape( ...
            frameSymbols, ...
            NFFT, 1);

        % Perform OFDM modulation.
        frameWithCP = ofdmmod( ...
            frameSymbols, ...
            NFFT, ...
            cpLength);

        % Pass the signal through the Rayleigh channel.
        [fadedSignal, pathGains] = ...
            qamChannel(frameWithCP);

        % Compensate for channel timing offset.
        fadedSignalSync = [ ...
            fadedSignal(qamTimingOffset+1:end); ...
            zeros(qamTimingOffset,1)];

        % Add AWGN noise.
        receivedSignal = awgn( ...
            fadedSignalSync, ...
            currentSNR, ...
            'measured');

        % Calculate the channel frequency response.
        channelResponse = ofdmChannelResponse( ...
            pathGains, ...
            qamPathFilters, ...
            NFFT, ...
            cpLength, ...
            1:NFFT, ...
            qamTimingOffset);

        % Convert channel response to a column vector.
        channelResponse = reshape( ...
            channelResponse, ...
            NFFT, 1);

        % Perform OFDM demodulation.
        receivedSymbols = ofdmdemod( ...
            receivedSignal, ...
            NFFT, ...
            cpLength, ...
            cpLength/2);

        % Convert received symbols into a column vector.
        receivedSymbols = reshape( ...
            receivedSymbols, ...
            NFFT, 1);

        % Perform frequency-domain channel equalization.
        equalizedSymbols = ...
            receivedSymbols ./ channelResponse;

        % Demodulate the equalized 16-QAM symbols.
        receivedBits = qamdemod( ...
            equalizedSymbols, ...
            16, ...
            OutputType="bit", ...
            UnitAveragePower=true);

        % Calculate bit errors.
        [frameErrors, ~] = biterr( ...
            frameBits, ...
            receivedBits);

        % Accumulate errors.
        totalErrors = ...
            totalErrors + frameErrors;

        % Accumulate transmitted bits.
        totalBits = ...
            totalBits + length(frameBits);

    end

    % Calculate BER.
    BER_16QAM_Rayleigh(i) = ...
        totalErrors / totalBits;

end

%% ============================================================
%  PART 4: 16-QAM + DOPPLER RAYLEIGH
% =============================================================

% Create an array to store Doppler BER values.
BER_16QAM_Doppler = zeros(size(SNR_values));

% Repeat the experiment for every SNR value.
for i = 1:length(SNR_values)

    % Set the current SNR.
    currentSNR = SNR_values(i);

    % Reset total errors.
    totalErrors = 0;

    % Reset total transmitted bits.
    totalBits = 0;

    % Create a two-path Doppler Rayleigh channel.
    dopplerChannel = comm.RayleighChannel( ...
        SampleRate=1e6, ...
        PathDelays=[0 1e-6], ...
        AveragePathGains=[0 -3], ...
        MaximumDopplerShift=100, ...
        PathGainsOutputPort=true);

    % Get channel information.
    dopplerInfo = info(dopplerChannel);

    % Get channel filter coefficients.
    dopplerPathFilters = ...
        dopplerInfo.ChannelFilterCoefficients;

    % Get timing offset.
    dopplerTimingOffset = ...
        dopplerInfo.ChannelFilterDelay;

    % Simulate many OFDM frames.
    for frame = 1:numFrames

        % Generate random bits.
        frameBits = randi( ...
            [0 1], ...
            NFFT * 4, ...
            1);

        % Perform 16-QAM modulation.
        frameSymbols = qammod( ...
            frameBits, ...
            16, ...
            InputType="bit", ...
            UnitAveragePower=true);

        % Arrange symbols into one OFDM symbol.
        frameSymbols = reshape( ...
            frameSymbols, ...
            NFFT, 1);

        % Perform OFDM modulation.
        frameWithCP = ofdmmod( ...
            frameSymbols, ...
            NFFT, ...
            cpLength);

        % Pass signal through Doppler Rayleigh channel.
        [fadedSignal, pathGains] = ...
            dopplerChannel(frameWithCP);

        % Compensate for timing offset.
        fadedSignalSync = [ ...
            fadedSignal(dopplerTimingOffset+1:end); ...
            zeros(dopplerTimingOffset,1)];

        % Add AWGN noise.
        receivedSignal = awgn( ...
            fadedSignalSync, ...
            currentSNR, ...
            'measured');

        % Calculate the Doppler channel frequency response.
        channelResponse = ofdmChannelResponse( ...
            pathGains, ...
            dopplerPathFilters, ...
            NFFT, ...
            cpLength, ...
            1:NFFT, ...
            dopplerTimingOffset);

        % Convert channel response to a column vector.
        channelResponse = reshape( ...
            channelResponse, ...
            NFFT, 1);

        % Perform OFDM demodulation.
        receivedSymbols = ofdmdemod( ...
            receivedSignal, ...
            NFFT, ...
            cpLength, ...
            cpLength/2);

        % Convert received symbols to a column vector.
        receivedSymbols = reshape( ...
            receivedSymbols, ...
            NFFT, 1);

        % Perform channel equalization.
        equalizedSymbols = ...
            receivedSymbols ./ channelResponse;

        % Demodulate the 16-QAM symbols.
        receivedBits = qamdemod( ...
            equalizedSymbols, ...
            16, ...
            OutputType="bit", ...
            UnitAveragePower=true);

        % Calculate bit errors.
        [frameErrors, ~] = biterr( ...
            frameBits, ...
            receivedBits);

        % Accumulate errors.
        totalErrors = ...
            totalErrors + frameErrors;

        % Accumulate transmitted bits.
        totalBits = ...
            totalBits + length(frameBits);

    end

    % Calculate BER for this SNR.
    BER_16QAM_Doppler(i) = ...
        totalErrors / totalBits;

end

%% ============================================================
%  PART 5: FINAL PERFORMANCE COMPARISON
% =============================================================

% Create the final comparison graph.
figure;

% Plot QPSK with static Rayleigh.
semilogy( ...
    SNR_values, ...
    BER_QPSK_Rayleigh, ...
    'o-');

% Keep the current graph so another curve can be added.
hold on;

% Plot 16-QAM with static Rayleigh.
semilogy( ...
    SNR_values, ...
    BER_16QAM_Rayleigh, ...
    's-');

% Plot 16-QAM with Doppler Rayleigh.
semilogy( ...
    SNR_values, ...
    BER_16QAM_Doppler, ...
    '^-');

% Label the horizontal axis.
xlabel('SNR (dB)');

% Label the vertical axis.
ylabel('Bit Error Rate (BER)');

% Give the graph a title.
title('Final OFDM Wireless System Performance');

% Identify each curve.
legend( ...
    'QPSK + Static Rayleigh', ...
    '16-QAM + Static Rayleigh', ...
    '16-QAM + Doppler Rayleigh');

% Display grid lines.
grid on;

%% ============================================================
%  PART 6: FINAL BER RESULTS TABLE
% =============================================================

% Convert SNR values into a column.
SNR_Final = SNR_values';

% Convert QPSK BER values into a column.
QPSK_Static_Rayleigh = ...
    BER_QPSK_Rayleigh';

% Convert 16-QAM static Rayleigh values into a column.
QAM16_Static_Rayleigh = ...
    BER_16QAM_Rayleigh';

% Convert 16-QAM Doppler values into a column.
QAM16_Doppler_Rayleigh = ...
    BER_16QAM_Doppler';

% Create a MATLAB table containing the final results.
FinalResults = table( ...
    SNR_Final, ...
    QPSK_Static_Rayleigh, ...
    QAM16_Static_Rayleigh, ...
    QAM16_Doppler_Rayleigh);

% Display a heading.
disp(' ');

% Display the final results heading.
disp('===== FINAL OFDM BER RESULTS =====');

% Display the table.
disp(FinalResults);